#!/usr/bin/env sh

# Created by wcl, modified by kortaol

if [ $# -ne 3 ] && [ $# -ne 4 ] || [ $1 = "-h" ]; then
	echo "(arch)Ive - a simple shell script for easier archive management"
	echo "Usage: ve [COMPRESSION_TYPE (tar or zip)] [ACTION (e for extract, a for archive)] [ARCHIVE_NAME] [FILES (if action is a)]"
	exit 0
fi;

case $1 in

    "tar")
	case $2 in
	    "e")
		tar -xvf $3
	    ;;
	    "a")
		tar -cvJf $3 $4
	    ;;
	    *)
		echo "Enter a valid action (e for extract, a for archive)"
	    ;;
	esac
    ;;

    "zip")
	case $2 in
	    "e")
		filename=$3
		unzip $3
	    ;;
	    "a")
		zip -r $3 $4
	    ;;
	    *)
		echo "Enter a valid action (e for extract, a for archive)"
	    ;;
	esac
    ;;

    "rar")
	case $2 in
	    "e")
		rar x $3
	    ;;
	    "a")
		rar -r a $3 $4
	    ;;
	    *)
		echo "Enter a valid action (e for extract, a for archive)"
	    ;;
	esac
    ;;

    *)
	echo "Enter a valid compression type (tar, rar or zip)"
    ;;
esac
